# Use SEGGER RTT as backend
CONFIG_USE_SEGGER_RTT=y

# Route console/printk over RTT instead of UART
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_STDOUT_CONSOLE=y

# Enable floating-point support for printf
CONFIG_CBPRINTF_FP_SUPPORT=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

